sudo: false
dist: trusty
cache:
  directories:
    - "$HOME/.m2"
language: java
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - unset _JAVA_OPTIONS
install: true
env:
  global:
    - MAVEN_OPTS=-Xmx512m
script:
  - mvn -B -fae -Dall clean install -T1C $ARGS
notifications:
  email: false
  on_failure: never
addons:
  apt:
    packages:
      - python-sphinx
      - libgdal1h
matrix:
  include:
    - jdk: oraclejdk8
      env: ARGS="-Dfmt.skip=true"
    - jdk: oraclejdk11
      env: ARGS="-Dfmt.skip=true"
    - jdk: oraclejdk8
      env: ARGS="-Dfmt.action=check -Ppmd -DskipTests=true"
