sudo: false
dist: trusty
cache:
  directories:
    - "$HOME/.m2"
language: java
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - unset _JAVA_OPTIONS
install: true
env:
  global:
    - MAVEN_OPTS=-Xmx512m
script:
  - mvn -B -fae -T4 -Dall clean install -Dfmt.action=check
notifications:
  email: false
  on_failure: never
jdk: 
  - oraclejdk8
  - oraclejdk11
addons:
  apt:
    packages:
      - python-sphinx
      - libgdal1h
