name: Downstream integration build (GeoWebCache and GeoServer)

on:
  # trigger on PR, but only on main branch, the checkouts of the downstream projects are also targeting main (default branch)
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'temurin'
    - uses: actions/checkout@v2
    - name: Maven repository caching
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gt-maven-
    - name: Disable checksum offloading
      # See: https://github.com/actions/virtual-environments/issues/1187#issuecomment-686735760
      run: sudo ethtool -K eth0 tx off rx off
    - name: Build GeoTools (no tests, prepare fresh artifacts)
      run: mvn -B clean install -T2 -Dall --file pom.xml -DskipTests
    - name: Checkout GeoWebCache and GeoServer
      run: |
        cd ~
        echo "Preparing git ssh checkouts"
        mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        echo "Checking out GeoWebCache"
        mkdir geowebcache
        git clone https://github.com/GeoWebCache/geowebcache.git geowebcache
        echo "Checking out GeoServer"
        mkdir geoserver
        git clone https://github.com/geoserver/geoserver.git geoserver
    - name: Build GeoWebCache with tests
      run: |
        export TEST_OPTS="-XX:+UseStringDeduplication -XX:+UseG1GC -XX:MaxHeapFreeRatio=30 -XX:MinHeapFreeRatio=10"
        export MAVEN_OPTS="-Xmx512m $TEST_OPTS"
        cd ~
        mvn -B -f geowebcache/geowebcache/pom.xml install -nsu -Dspotless.apply.skip=true -DskipTests
        mvn -B -f geowebcache/geowebcache/pom.xml test -nsu -T2 -Dspotless.apply.skip=true
    - name: Build GeoServer with tests
      run: |
        export TEST_OPTS="-XX:+UseStringDeduplication -XX:+UseG1GC -XX:MaxHeapFreeRatio=30 -XX:MinHeapFreeRatio=10"
        export MAVEN_OPTS="-Xmx512m $TEST_OPTS"
        cd ~
        mvn -B -f geoserver/src/pom.xml install -nsu -Prelease -Dspotless.apply.skip=true -DskipTests
        mvn -B -f geoserver/src/community/pom.xml install -nsu -DcommunityRelease -Dspotless.apply.skip=true -DskipTests
        mvn -B -f geoserver/src/pom.xml test -T2 -nsu -Dtest.maxHeapSize=512m -Djvm.opts="$TEST_OPTS" -Prelease -Dspotless.apply.skip=true
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {} 
