name: Linux JDK 17 Locales GitHub CI

on: [pull_request]

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [ubuntu-24.04]
    strategy:
      fail-fast: false
      matrix:
        # italian has . and , usage opposite to english. More languages can be added as needed.
        locale: [it_IT.UTF-8]
    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Maven repository caching
      uses: actions/cache@v5
      with:
        path: ~/.m2/repository
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gt-maven-
    - name: Disable checksum offloading
      # See: https://github.com/actions/virtual-environments/issues/1187#issuecomment-686735760
      run: sudo ethtool -K eth0 tx off rx off
    - name: Install locales
      run: |
        sudo apt-get update
        sudo apt-get install -y locales
        sudo locale-gen en_US.UTF-8 it_IT.UTF-8 tr_TR.UTF-8
        sudo update-locale

    - name: Set locale
      run: |
        echo "LANG=${{ matrix.locale }}" >> $GITHUB_ENV
        echo "LC_ALL=${{ matrix.locale }}" >> $GITHUB_ENV
        echo "LC_NUMERIC=${{ matrix.locale }}" >> $GITHUB_ENV
        locale
    - name: Build with Maven
      run: |
        mvn -B clean install -Dspotless.apply.skip=true -Dall -T1C -U -Plinux-github-build -fae --file pom.xml
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
