name: Oracle online tests

on: [pull_request]

jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: [ubuntu-18.04]
    strategy:
      matrix:
        java: [11]

    steps:
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/checkout@v2
    - name: Maven repository caching
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: oracle-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          oracle-${{ runner.os }}-maven-
    - name: Free up diskspace
      run: |
        docker container prune --force
        docker image prune -a --force
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet 
        df -h
    - name: Setup test environment for Oracle XE 
      run: |
        ./build/ci/oracle/start-oracle.sh
        ./build/ci/oracle/setup-oracle.sh
    - name: Build GeoTools dependent modules (no tests)
      run: mvn -B clean install -T2 -Dall -pl :gt-jdbc-oracle -DskipTests -am
    - name: Test Oracle data store
      run: mvn -B clean install -pl :gt-jdbc-oracle -Pci-oracle-build -Ponline -Dfmt.skip=true
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
