name: Oracle online tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Java ${{ matrix.java }} / Oracle ${{ matrix.oracle }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [ 11 ]
        oracle: [ 'oracle-xe:21.3.0', 'oracle-free:23.9' ]
      fail-fast: false

    steps:
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - uses: actions/checkout@v6

    - name: Maven repository caching
      uses: actions/cache@v5
      with:
        path: ~/.m2/repository
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gt-maven-

    - name: Setup test environment for ${{ matrix.oracle }}
      run: |
        ./build/ci/oracle/start-oracle.sh ${{ matrix.oracle }}
        ./build/ci/oracle/setup-oracle.sh

    - name: Build GeoTools dependent modules (no tests)
      run: mvn -B clean install -T1C -Dall -pl :gt-jdbc-oracle -DskipTests -am

    - name: Test Oracle data store
      run: mvn -B clean install -pl :gt-jdbc-oracle -Pci-oracle-build -Ponline -Dspotless.apply.skip=true

    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
