name: PostGIS online tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgis: [ 11-3.3, 18-3.6 ]
        java: [ 17 ]

    steps:
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - uses: actions/checkout@v6
    - name: Maven repository caching
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gt-maven-
    - name: Setup test environment for PostGIS ${{ matrix.postgis }}
      run: |
        ./build/ci/postgis/start-postgis.sh ${{ matrix.postgis }}
        ./build/ci/postgis/setup-postgis.sh
    - name: Build GeoTools dependent modules (no tests, prepare fresh artifacts)
      run: mvn -B clean install -T1C -U -Dall --file pom.xml -DskipTests -pl modules/plugin/jdbc/jdbc-postgis,modules/plugin/imagemosaic -am -Dspotless.apply.skip=true
    - name: Build PostGIS data store with online tests
      run: |
        mvn -B clean install -pl modules/plugin/jdbc/jdbc-postgis -Ponline -nsu
        mvn -B clean install -pl modules/plugin/imagemosaic -Ponline -nsu
    - name: Remove SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {} 
